// SPDX-License-Identifier: GPL-2.0-only
/*
 * bpf_loader.c - eBPF program loader and ring buffer interface
 *
 * Opens, loads, and attaches all three owlbear BPF skeletons.
 * Graceful degradation: each skeleton is independent. If LSM hooks
 * fail (missing CONFIG_BPF_LSM), kprobe detection still works.
 */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include <bpf/libbpf.h>
#include <bpf/bpf.h>

#include "bpf_loader.h"

/* Skeleton headers generated by bpftool */
#include "owlbear_lsm.skel.h"
#include "owlbear_trace.skel.h"
#include "owlbear_kprobe.skel.h"

/*
 * BPF event structure — must match owlbear_common.bpf.h.
 * Duplicated here because the BPF header uses vmlinux.h types.
 */
struct owl_bpf_event {
	uint64_t timestamp_ns;
	uint32_t event_type;
	uint32_t severity;
	uint32_t pid;
	uint32_t target_pid;
	char     comm[16];
	char     detail[48];
};

struct owl_bpf_ctx {
	struct owlbear_lsm_bpf    *lsm;
	struct owlbear_trace_bpf  *trace;
	struct owlbear_kprobe_bpf *kprobe;
	struct ring_buffer        *ringbuf;

	bool has_lsm;
	bool has_trace;
	bool has_kprobe;

	/* Map fds for populating from userspace */
	int protected_pids_fd;
	int allowed_pids_fd;

	/* User callback */
	owl_bpf_event_cb event_cb;
	void            *event_cb_ctx;
};

/* -------------------------------------------------------------------------
 * Pure conversion function (testable without BPF)
 * ----------------------------------------------------------------------- */

int owl_bpf_event_convert(const void *bpf_data, size_t bpf_size,
			   struct owlbear_event *out)
{
	if (!bpf_data || !out)
		return -1;

	if (bpf_size < sizeof(struct owl_bpf_event))
		return -1;

	const struct owl_bpf_event *bev = bpf_data;

	memset(out, 0, sizeof(*out));
	out->timestamp_ns = bev->timestamp_ns;
	out->event_type = bev->event_type;
	out->severity = bev->severity;
	out->source = OWL_SRC_EBPF;
	out->pid = bev->pid;
	out->target_pid = bev->target_pid;
	memcpy(out->comm, bev->comm, sizeof(out->comm));

	/*
	 * Map the detail string into the appropriate payload union
	 * based on event type.
	 */
	switch (bev->event_type) {
	case OWL_EVENT_PTRACE_ATTEMPT:
	case OWL_EVENT_PROC_MEM_ACCESS:
	case OWL_EVENT_VM_READV_ATTEMPT:
	case OWL_EVENT_VM_WRITEV_ATTEMPT:
	case OWL_EVENT_MPROTECT_EXEC:
		out->payload.memory.caller_pid = bev->pid;
		memcpy(out->payload.memory.caller_comm, bev->comm,
		       sizeof(out->payload.memory.caller_comm) < sizeof(bev->comm)
		       ? sizeof(out->payload.memory.caller_comm)
		       : sizeof(bev->comm));
		break;

	case OWL_EVENT_MODULE_LOAD:
		memcpy(out->payload.module.name, bev->detail,
		       sizeof(out->payload.module.name) < sizeof(bev->detail)
		       ? sizeof(out->payload.module.name)
		       : sizeof(bev->detail));
		break;

	default:
		/* Copy detail into raw payload as fallback */
		memcpy(out->payload.raw, bev->detail,
		       sizeof(out->payload.raw) < sizeof(bev->detail)
		       ? sizeof(out->payload.raw)
		       : sizeof(bev->detail));
		break;
	}

	return 0;
}

/* -------------------------------------------------------------------------
 * Ring buffer callback — invoked by libbpf for each event
 * ----------------------------------------------------------------------- */

static int ringbuf_event_handler(void *ctx, void *data, size_t data_sz)
{
	struct owl_bpf_ctx *bctx = ctx;
	struct owlbear_event ev;

	if (owl_bpf_event_convert(data, data_sz, &ev) < 0)
		return 0;  /* Skip malformed events */

	if (bctx->event_cb)
		bctx->event_cb(&ev, bctx->event_cb_ctx);

	return 0;
}

/* -------------------------------------------------------------------------
 * Libbpf log callback — suppress noisy output unless debug
 * ----------------------------------------------------------------------- */

static int libbpf_print_fn(enum libbpf_print_level level,
			    const char *format, va_list args)
{
	if (level == LIBBPF_DEBUG)
		return 0;
	return vfprintf(stderr, format, args);
}

/* -------------------------------------------------------------------------
 * Map fd extraction — find the protected_pids fd from whichever
 * skeleton loaded first (maps are shared via BTF map pinning).
 * ----------------------------------------------------------------------- */

static int find_map_fd(struct owl_bpf_ctx *ctx, const char *name)
{
	int fd = -1;

	if (ctx->lsm) {
		struct bpf_map *map = bpf_object__find_map_by_name(
			ctx->lsm->obj, name);
		if (map)
			fd = bpf_map__fd(map);
	}

	if (fd < 0 && ctx->trace) {
		struct bpf_map *map = bpf_object__find_map_by_name(
			ctx->trace->obj, name);
		if (map)
			fd = bpf_map__fd(map);
	}

	if (fd < 0 && ctx->kprobe) {
		struct bpf_map *map = bpf_object__find_map_by_name(
			ctx->kprobe->obj, name);
		if (map)
			fd = bpf_map__fd(map);
	}

	return fd;
}

/* -------------------------------------------------------------------------
 * Public API
 * ----------------------------------------------------------------------- */

struct owl_bpf_ctx *owl_bpf_init(owl_bpf_event_cb cb, void *cb_ctx)
{
	struct owl_bpf_ctx *ctx;
	int err;

	ctx = calloc(1, sizeof(*ctx));
	if (!ctx)
		return NULL;

	ctx->event_cb = cb;
	ctx->event_cb_ctx = cb_ctx;
	ctx->protected_pids_fd = -1;
	ctx->allowed_pids_fd = -1;

	libbpf_set_print(libbpf_print_fn);

	/* --- LSM skeleton --- */
	ctx->lsm = owlbear_lsm_bpf__open_and_load();
	if (!ctx->lsm) {
		fprintf(stderr, "owlbeard: BPF LSM load failed: %s\n",
			strerror(errno));
	} else {
		err = owlbear_lsm_bpf__attach(ctx->lsm);
		if (err) {
			fprintf(stderr, "owlbeard: BPF LSM attach failed: %s\n",
				strerror(-err));
			owlbear_lsm_bpf__destroy(ctx->lsm);
			ctx->lsm = NULL;
		} else {
			ctx->has_lsm = true;
			printf("owlbeard: BPF LSM programs attached\n");
		}
	}

	/* --- Tracepoint skeleton --- */
	ctx->trace = owlbear_trace_bpf__open_and_load();
	if (!ctx->trace) {
		fprintf(stderr, "owlbeard: BPF trace load failed: %s\n",
			strerror(errno));
	} else {
		err = owlbear_trace_bpf__attach(ctx->trace);
		if (err) {
			fprintf(stderr, "owlbeard: BPF trace attach failed: %s\n",
				strerror(-err));
			owlbear_trace_bpf__destroy(ctx->trace);
			ctx->trace = NULL;
		} else {
			ctx->has_trace = true;
			printf("owlbeard: BPF tracepoint programs attached\n");
		}
	}

	/* --- Kprobe skeleton --- */
	ctx->kprobe = owlbear_kprobe_bpf__open_and_load();
	if (!ctx->kprobe) {
		fprintf(stderr, "owlbeard: BPF kprobe load failed: %s\n",
			strerror(errno));
	} else {
		err = owlbear_kprobe_bpf__attach(ctx->kprobe);
		if (err) {
			fprintf(stderr, "owlbeard: BPF kprobe attach failed: %s\n",
				strerror(-err));
			owlbear_kprobe_bpf__destroy(ctx->kprobe);
			ctx->kprobe = NULL;
		} else {
			ctx->has_kprobe = true;
			printf("owlbeard: BPF kprobe programs attached\n");
		}
	}

	/* If nothing loaded, still return ctx (degraded mode) */
	if (!ctx->has_lsm && !ctx->has_trace && !ctx->has_kprobe) {
		fprintf(stderr, "owlbeard: WARNING: no BPF programs loaded, "
			"running in kmod-only mode\n");
	}

	/* Extract map fds */
	ctx->protected_pids_fd = find_map_fd(ctx, "protected_pids");
	ctx->allowed_pids_fd = find_map_fd(ctx, "allowed_pids");

	/* Set up ring buffer */
	int events_fd = find_map_fd(ctx, "events");
	if (events_fd >= 0) {
		ctx->ringbuf = ring_buffer__new(events_fd,
						ringbuf_event_handler,
						ctx, NULL);
		if (!ctx->ringbuf) {
			fprintf(stderr, "owlbeard: ring buffer setup failed\n");
		}
	}

	return ctx;
}

void owl_bpf_destroy(struct owl_bpf_ctx *ctx)
{
	if (!ctx)
		return;

	if (ctx->ringbuf)
		ring_buffer__free(ctx->ringbuf);

	if (ctx->lsm)
		owlbear_lsm_bpf__destroy(ctx->lsm);
	if (ctx->trace)
		owlbear_trace_bpf__destroy(ctx->trace);
	if (ctx->kprobe)
		owlbear_kprobe_bpf__destroy(ctx->kprobe);

	free(ctx);
}

int owl_bpf_protect_pid(struct owl_bpf_ctx *ctx, uint32_t pid)
{
	if (!ctx || ctx->protected_pids_fd < 0)
		return -1;

	uint32_t flags = 0;
	return bpf_map_update_elem(ctx->protected_pids_fd, &pid, &flags, BPF_ANY);
}

int owl_bpf_allow_pid(struct owl_bpf_ctx *ctx, uint32_t pid)
{
	if (!ctx || ctx->allowed_pids_fd < 0)
		return -1;

	uint32_t level = 1;
	return bpf_map_update_elem(ctx->allowed_pids_fd, &pid, &level, BPF_ANY);
}

int owl_bpf_ringbuf_fd(const struct owl_bpf_ctx *ctx)
{
	if (!ctx || !ctx->ringbuf)
		return -1;

	return ring_buffer__epoll_fd(ctx->ringbuf);
}

int owl_bpf_poll(struct owl_bpf_ctx *ctx, int timeout_ms)
{
	if (!ctx || !ctx->ringbuf)
		return 0;

	return ring_buffer__poll(ctx->ringbuf, timeout_ms);
}

bool owl_bpf_has_lsm(const struct owl_bpf_ctx *ctx)
{
	return ctx && ctx->has_lsm;
}

bool owl_bpf_has_trace(const struct owl_bpf_ctx *ctx)
{
	return ctx && ctx->has_trace;
}

bool owl_bpf_has_kprobe(const struct owl_bpf_ctx *ctx)
{
	return ctx && ctx->has_kprobe;
}
